import StyleDictionary from "style-dictionary";

// Helper to get token value (supports DTCG format)
const getValue = (token) => token.$value ?? token.value;

// Custom format for CSS custom properties with ds- prefix
StyleDictionary.registerFormat({
  name: "css/ds-variables",
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens
      .map((token) => {
        const name = token.path.join("-");
        return `  --ds-${name}: ${getValue(token)};`;
      })
      .join("\n");

    return `:root {\n${tokens}\n}\n`;
  },
});

// Format for dark mode CSS
StyleDictionary.registerFormat({
  name: "css/ds-dark-mode",
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens
      .map((token) => {
        const name = token.path.join("-");
        return `    --ds-${name}: ${getValue(token)};`;
      })
      .join("\n");

    return `@media (prefers-color-scheme: dark) {\n  :root {\n${tokens}\n  }\n}\n\n[data-theme="dark"] {\n${tokens.replace(/ {4}/g, "  ")}\n}\n`;
  },
});

// Format for high-contrast mode CSS
StyleDictionary.registerFormat({
  name: "css/ds-high-contrast",
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens
      .map((token) => {
        const name = token.path.join("-");
        return `    --ds-${name}: ${getValue(token)};`;
      })
      .join("\n");

    return `@media (prefers-contrast: more) {\n  :root {\n${tokens}\n  }\n}\n\n[data-theme="high-contrast"] {\n${tokens.replace(/ {4}/g, "  ")}\n}\n`;
  },
});

// Format for TypeScript constants
StyleDictionary.registerFormat({
  name: "ts/ds-constants",
  format: ({ dictionary }) => {
    const buildObject = (tokens) => {
      const result = {};
      for (const token of tokens) {
        let current = result;
        for (let i = 0; i < token.path.length - 1; i++) {
          const key = token.path[i];
          if (!current[key]) {
            current[key] = {};
          }
          current = current[key];
        }
        current[token.path[token.path.length - 1]] = getValue(token);
      }
      return result;
    };

    const tokensObj = buildObject(dictionary.allTokens);
    return `// Auto-generated by Style Dictionary\n// Do not edit manually\n\nexport const tokens = ${JSON.stringify(tokensObj, null, 2)} as const;\n\nexport type Tokens = typeof tokens;\n`;
  },
});

// Custom transform for CSS variable references
StyleDictionary.registerTransform({
  name: "css/references",
  type: "value",
  transitive: true,
  filter: (token) => {
    return typeof token.value === "string" && token.value.startsWith("{");
  },
  transform: (token) => {
    const value = token.value;
    if (typeof value === "string" && value.startsWith("{") && value.endsWith("}")) {
      const path = value.slice(1, -1).replace(/\./g, "-");
      return `var(--ds-${path})`;
    }
    return value;
  },
});

export default {
  source: ["src/tokens/primitives/**/*.json", "src/tokens/semantic/**/*.json"],
  parsers: ["json5-parser"],
  usesDtcg: true,
  platforms: {
    css: {
      transforms: ["css/references", "name/kebab"],
      buildPath: "dist/css/",
      files: [
        {
          destination: "tokens.css",
          format: "css/ds-variables",
        },
      ],
    },
    ts: {
      transforms: ["name/camel"],
      buildPath: "dist/ts/",
      files: [
        {
          destination: "tokens.ts",
          format: "ts/ds-constants",
        },
      ],
    },
  },
};

// Separate configs for mode files
export const darkModeConfig = {
  source: ["src/tokens/primitives/**/*.json", "src/tokens/modes/dark.json"],
  usesDtcg: true,
  platforms: {
    css: {
      transforms: ["css/references", "name/kebab"],
      buildPath: "dist/css/",
      files: [
        {
          destination: "dark.css",
          format: "css/ds-dark-mode",
          filter: (token) => token.filePath.includes("dark.json"),
        },
      ],
    },
  },
};

export const highContrastConfig = {
  source: ["src/tokens/primitives/**/*.json", "src/tokens/modes/high-contrast.json"],
  usesDtcg: true,
  platforms: {
    css: {
      transforms: ["css/references", "name/kebab"],
      buildPath: "dist/css/",
      files: [
        {
          destination: "high-contrast.css",
          format: "css/ds-high-contrast",
          filter: (token) => token.filePath.includes("high-contrast.json"),
        },
      ],
    },
  },
};
